### PR TITLE
Symlink downloader concurrency

### PR DESCRIPTION
**Pull request by Gaisberg**
- Symlink downloader performance improvements
- delete endpoint now listens to configured finishedaction settings
- readme section for symlink downloader

### CODE REVIEW

**Comment by dreulavelle** [comment]
Also waiting on this @rogerfar 

Have you gotten a chance to take a look at this?

**Comment by rogerfar** [comment]
@dreulavelle I merged your PR, but I will have to do some thorough testing on the TorrentRunner as it's a complicated state machine that I don't want to break with other downloaders. Unfortunately I'm pretty busy so it will take a few weeks to get that sorted.

**Comment by Gaisberg** [comment]
There are still concurrency issues, please test thorougly. Ill try and figure it out...

**Comment by rogerfar** [comment]
I have pushed a new build with your changes in the downloader alone.

**Comment by Gaisberg** [comment]
Im guessing its because we never push download.link to _dataContext.

Ill test it out and get back to you. In the meantime I would love for you to join plex-debrid discord, we have a nice forum regarding rdt-client.

**Pull request merged**
