### PR TITLE
Updates to Docker Build Process

### PR DESCRIPTION
**Pull request by ravensorb**
Converted main image to be based on alpine.
Added HEALTHCHECK to Dockerfile
Small fixes to powershell scripts

### CODE REVIEW

**Comment by rogerfar** [comment]
Is it expected we're not exposing /config anymore as a volume?

**Comment by ravensorb** [comment]
Good question -- from what I can tell that volume is no longer been used for anything in this specific app/container.  The standard format for linuxserver.io images is to use /config for related to runtime data (databases, config files, etc).  When I took a bit of a look at how rdt-client is working it uses /data for a lot of that instead.  Does that sound right to you as well?

**Comment by rogerfar** [comment]
You're right, not sure why that was ever exposed. I'll make a new build.

**Comment by ravensorb** [comment]
Interesting.  Switching to alpine should result in some improvement -- however not sure I would expect that significant of one though.  Lets see what the feedback is from the community.

**Pull request merged**
