### PR TITLE
Updates to docker image related to issue 214

### PR DESCRIPTION
**Pull request by ravensorb**
Changes include
* Update dockerfile to use newer node image for building client frontend
* Updated build scripts
* Updated files for s6overlay for when the rdt-client service starts
* Added initial version of github actions workflow to build and publish image

### CODE REVIEW

**Comment by rogerfar** [comment]
I'm getting this error when trying to build:
```
#0 0.252 /bin/sh: git: not found
```
Maybe `node:16-alpine3.17` has no git installed?

**Comment by ravensorb** [comment]
Hmm, good question.  I was using a modified Dockerfile that uses the COPY (from the local host rather than pulling from the main repo).  I can check in the Dockerfile that builds using the COPY (vs the git pull) if you want?

**Comment by rogerfar** [comment]
@ravensorb Do you mind having a look at the dockerfile if you have time? I did a push today but I'm getting:
```
buildx failed with: ERROR: failed to solve: ghcr.io/linuxserver/baseimage-alpine:3.18: no match for platform in manifest sha256:ac87cc359509acb73e5bf265a1e8dc3b554a6818cdb509479f30dc9cef2f0759: not found
```
I tried upgrading to 3.18, but that didn't seem to make a difference.

**Comment by ravensorb** [comment]
Looks like support for arm7 has been dropped from the base alpine image (it is 32bit if I remember correctly).  Can we remove that from the list of platforms to build?

**Pull request merged**
